### ISSUE TITLE
Material Action Sheet

### ISSUE THREAD

**Issue by ItzNotABug** [chrs1885/SheetyColors#16]
> Please fill out all lines starting with a 📝 when filing a feature request to give us an idea of what exactly went wrong.

## What kind of feature would you like to see?
📝Would be great if we can use this cool colour picker inside a Material Action Sheet by Google.
And using Material Sliders.

## How does it work in detail?
📝

## What does the API look like?
📝https://material.io/develop/ios/components/action-sheet/
https://material.io/develop/ios/components/sliders/

## Any existing projects that do something similiar?
📝Not that I'm aware of.

**Comment by chrs1885** [comment]
@ItzNotABug first and foremost thanks for the request.

To be honest, without getting help from the community on this one, the feature you requested will probably not be part of the lib anytime soon, since I'm working on other features with a higher prio right now. Would you like to submit a pull request?

**Comment by ItzNotABug** [comment]
Would have submitted a PR but I'm still new to iOS & learning a lot of stuff.
Thanks anyway and cheers for this cool library!. 🥳

**Comment by chrs1885** [comment]
@ItzNotABug I'm going to close this for now. Thanks for sharing your ideas, though. Maybe we get back to this one at some point :+1:
